import { Provider } from './types'

export const PROVIDERS: Provider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    prefixes: ['sk-proj-', 'sk-'],
    color: '#10a37f',
    domain: 'openai.com',
    docsUrl: 'https://platform.openai.com/docs',
    verifyEndpoint: 'https://api.openai.com/v1/models',
    requiresProxy: false,
    icon: '🤖',
    model: 'openai/gpt-4o',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    prefixes: ['sk-ant-'],
    color: '#d97757',
    domain: 'anthropic.com',
    docsUrl: 'https://docs.anthropic.com',
    verifyEndpoint: 'https://api.anthropic.com/v1/models',
    requiresProxy: false,
    icon: '🧠',
    model: 'anthropic/claude-3-5-sonnet',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    prefixes: ['AIza'],
    color: '#4285f4',
    domain: 'ai.google.dev',
    docsUrl: 'https://ai.google.dev',
    verifyEndpoint: 'https://generativelanguage.googleapis.com/v1beta/models',
    requiresProxy: false,
    icon: '♊',
    model: 'google/gemini-1.5-pro',
  },
  {
    id: 'groq',
    name: 'Groq',
    prefixes: ['gsk_'],
    color: '#f55036',
    domain: 'groq.com',
    docsUrl: 'https://console.groq.com/docs',
    verifyEndpoint: 'https://api.groq.com/openai/v1/models',
    requiresProxy: false,
    icon: '⚡',
    model: 'groq/llama-3.1-70b',
  },
  {
    id: 'huggingface',
    name: 'HuggingFace',
    prefixes: ['hf_'],
    color: '#ff9d00',
    domain: 'huggingface.co',
    docsUrl: 'https://huggingface.co/docs',
    verifyEndpoint: 'https://huggingface.co/api/whoami',
    requiresProxy: false,
    icon: '🤗',
    model: 'hf/meta-llama-3',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    prefixes: ['r8_'],
    color: '#ffffff',
    domain: 'replicate.com',
    docsUrl: 'https://replicate.com/docs',
    verifyEndpoint: 'https://api.replicate.com/v1/account',
    requiresProxy: false,
    icon: '🚀',
    model: 'replicate/stable-diffusion',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    prefixes: ['pplx-'],
    color: '#20b2aa',
    domain: 'perplexity.ai',
    docsUrl: 'https://docs.perplexity.ai',
    verifyEndpoint: 'https://api.perplexity.ai/models',
    requiresProxy: true,
    icon: '🔍',
    model: 'pplx/sonar-medium',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    prefixes: [],
    color: '#ff7000',
    domain: 'mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    verifyEndpoint: 'https://api.mistral.ai/v1/models',
    requiresProxy: true,
    icon: '🌪️',
    model: 'mistral/mistral-large',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    prefixes: [],
    color: '#39594d',
    domain: 'cohere.com',
    docsUrl: 'https://docs.cohere.com',
    verifyEndpoint: 'https://api.cohere.com/v1/models',
    requiresProxy: true,
    icon: '🤝',
    model: 'cohere/command-r',
  },
  {
    id: 'together',
    name: 'Together AI',
    prefixes: [],
    color: '#7c3aed',
    domain: 'together.ai',
    docsUrl: 'https://docs.together.ai',
    verifyEndpoint: 'https://api.together.xyz/v1/models',
    requiresProxy: true,
    icon: '🏗️',
    model: 'together/llama-3-70b',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    prefixes: [],
    color: '#9333ea',
    domain: 'elevenlabs.io',
    docsUrl: 'https://elevenlabs.io/docs',
    verifyEndpoint: 'https://api.elevenlabs.io/v1/user',
    requiresProxy: true,
    icon: '🗣️',
    model: 'elevenlabs/v1-voice',
  },
]

export const PROVIDERS_MAP = Object.fromEntries(PROVIDERS.map((p) => [p.id, p]))
