import { Provider } from './types'

export const PROVIDERS: Provider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    prefixes: ['sk-proj-', 'sk-'],
    color: '#10a37f',
    docsUrl: 'https://platform.openai.com/docs',
    verifyEndpoint: 'https://api.openai.com/v1/models',
    requiresProxy: false,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    prefixes: ['sk-ant-'],
    color: '#d97757',
    docsUrl: 'https://docs.anthropic.com',
    verifyEndpoint: 'https://api.anthropic.com/v1/models',
    requiresProxy: false,
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    prefixes: ['AIza'],
    color: '#4285f4',
    docsUrl: 'https://ai.google.dev',
    verifyEndpoint: 'https://generativelanguage.googleapis.com/v1beta/models',
    requiresProxy: false,
  },
  {
    id: 'groq',
    name: 'Groq',
    prefixes: ['gsk_'],
    color: '#f55036',
    docsUrl: 'https://console.groq.com/docs',
    verifyEndpoint: 'https://api.groq.com/openai/v1/models',
    requiresProxy: false,
  },
  {
    id: 'huggingface',
    name: 'HuggingFace',
    prefixes: ['hf_'],
    color: '#ff9d00',
    docsUrl: 'https://huggingface.co/docs',
    verifyEndpoint: 'https://huggingface.co/api/whoami',
    requiresProxy: false,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    prefixes: ['r8_'],
    color: '#ffffff',
    docsUrl: 'https://replicate.com/docs',
    verifyEndpoint: 'https://api.replicate.com/v1/account',
    requiresProxy: false,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    prefixes: ['pplx-'],
    color: '#20b2aa',
    docsUrl: 'https://docs.perplexity.ai',
    verifyEndpoint: 'https://api.perplexity.ai/models',
    requiresProxy: true,
  },
  {
    id: 'mistral',
    name: 'Mistral',
    prefixes: [],
    color: '#ff7000',
    docsUrl: 'https://docs.mistral.ai',
    verifyEndpoint: 'https://api.mistral.ai/v1/models',
    requiresProxy: true,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    prefixes: [],
    color: '#39594d',
    docsUrl: 'https://docs.cohere.com',
    verifyEndpoint: 'https://api.cohere.com/v1/models',
    requiresProxy: true,
  },
  {
    id: 'together',
    name: 'Together AI',
    prefixes: [],
    color: '#7c3aed',
    docsUrl: 'https://docs.together.ai',
    verifyEndpoint: 'https://api.together.xyz/v1/models',
    requiresProxy: true,
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    prefixes: [],
    color: '#9333ea',
    docsUrl: 'https://elevenlabs.io/docs',
    verifyEndpoint: 'https://api.elevenlabs.io/v1/user',
    requiresProxy: true,
  },
]

export const PROVIDERS_MAP = Object.fromEntries(PROVIDERS.map((p) => [p.id, p]))
